name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v3
    - name: Login to Docker
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file lockbox-notification-service/Dockerfile --tag rikdegoede/lockbox-notification-service:latest #my-image-name:$(date +%s)
    
    
